project_id = "ormnzqomurczsqapzpmi"

[functions.chat]
verify_jwt = false

[functions.api-ninjas-history]
verify_jwt = false

[functions.embed-content]
verify_jwt = false

[functions.rag-search]
verify_jwt = false

[functions.rag-chat]
verify_jwt = false
